name: utoolbox-dev

channels:
    - defaults
    - conda-forge

dependencies:
    # core
    - python=3.7

    # build tools
    #- bumpversion # development stalled, use bump2version
    - twine

    # linter
    - flake8
    
    # formatter
    - black
    
    # docs
    - sphinx
    - sphinx_rtd_theme

    # tests
    - pytest
    - coverage
    - pytest-cov

    # libraries from conda has mkl support
    - numpy
    - scipy

    # other pip dependencies
    - pip
    - pip: 
        - bump2version